### ISSUE TITLE
[bug] CCClippingNode does not clip during transition.

### ISSUE THREAD

**Issue by matthijn** [cocos2d/cocos2d-objc#610] opened 2014-02-22 21:48 UTC
Currently I am working on a game, and I am masking a sprite with the CCClippingNode, which I have working correctly but the clipping is not applied during a transition (e.g from and to the scene my clipping node is on). I have made a [small video](http://cl.ly/U3QF) which displays the problem. 

It looks like I am not the only one who has this problem, it is [described here](http://www.cocos2d-x.org/forums/6/topics/22633?r=24621) on the Cocos2d-X version. And [here](http://www.cocos2d-iphone.org/forums/topic/ccclippingnode-and-fade-transition/) is someone who has the problem with the iPhone version.

It would be nice if this could be fixed, because this greatly reduces the usability of the masking system in Cocos2d.

**Comment by slembcke** [comment] 2014-02-22 23:29
The problem is almost certainly because CCRenderTexture doesn't set up a stencil buffer (or z buffer). I'm not entirely certain it's possible to do so in GLES. Will have to look at the docs.

(edit: Yes, you can have a stencil attachment with a render texture FBO.)

**Comment by nilswx** [comment] 2014-02-23 12:27
Thanks for looking into this, slembcke. A shabby workaround for this use case is abandoning CCClippingNode (!) and actually cutting a circle out of the sprite (at runtime), and then just position the CCSprite in the scene.

Would love to see CCClipNode fixed though, as it's that much more convenient. I hope that it turns out to be possible with GLES.

**Comment by matthijn** [comment] 2014-03-22 17:48
I was wondering if anyone has taken the time to look in to this? We are still having this problem (RC4) and it would be nice if this could be fixed. I have tried to look in to it myself, but it looks like I don't have the expertise to see where it goes wrong.

**Comment by slembcke** [comment] 2014-04-03 20:29
I've started looking into making clipping node tests for the 3.1 renderer. I'll add a test for this. It looks like it might be pretty easy to fix. Stay tuned.

**Comment by matthijn** [comment] 2014-04-04 16:29
Nice. I've changed it for now in my game to use Core Graphics for masking. As advised by [Victor](http://forum.spritebuilder.com/t/ccclippingnode-does-not-clip-during-transition/737). But on my iPad 1 Cocos2d seems to be a tad bit faster. So it still would be nice if it could be fixed.

**Comment by slembcke** [comment] 2014-04-08 19:31
Fixed in the latest v3.0 branch.
https://github.com/cocos2d/cocos2d-iphone/commit/a9bd61f75e4bc0e8e4a0e02a7574f859724fb338

**Closed as completed by slembcke** 2014-04-08 19:31 UTC
Labels: Bug
