### ISSUE TITLE
Blur effect randomly doesn't work.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#985] opened 2014-09-17 22:14 UTC
Hmm. So after merging a couple of the effects pull requests I started noticing an issue with the blur node. If I refresh that test several times on my retina iPad mini, the two blurred versions will either randomly not show up or look oversaturated/clipped in weird ways. I got a screenshot of both happening above below. The arrow is all saturated, and the ring is missing.

![screen shot 2014-09-17 at 5 04 20 pm](https://cloud.githubusercontent.com/assets/153633/4312175/f6ad3262-3eb6-11e4-9fbc-372e82c7c7a3.png)

I also checked out 529ac53 which was before merging the pull requests and it seems to happen there too. That commit doesn't include the FBO changes I've made for Metal, so it's not that.

**Comment by thayerandrews** [comment] 2014-09-19 17:14
I've been able to reproduce this as well on the simulator. I'll take a look once I fix the [blur and bloom crashing in SpriteBuilder problem](https://github.com/spritebuilder/SpriteBuilder/issues/843).

**Comment by thayerandrews** [comment] 2014-09-22 22:52
Looks like we're indexing outside the gaussian weights array for certain blur radius values. I've discussed this with Oleg and am reassigning to him as he thinks it will be pretty easy to track down from here.

**Comment by osinoleg** [comment] 2014-09-23 23:33
fixed and submitted pull request: https://github.com/cocos2d/cocos2d-swift/pull/992

**Closed as completed** 2014-10-02 19:03 UTC
Labels: Bug
