### ISSUE TITLE
Crash in CCPhysicsBody when exiting scene with static object

### ISSUE THREAD

**Issue by iMobCoding** [cocos2d/cocos2d-objc#810] opened 2014-06-04 15:44 UTC
So make a simple scene in SpriteBuilder  with CCPhysicNode and one static object attached. Run in Xcode and try going to another scene. When OnExit is called, which calls teardownPhysics it crashes... Attached screen

![screen shot 2014-06-04 at 17 38 40](https://cloud.githubusercontent.com/assets/1320690/3175830/00d68820-ebff-11e3-828a-2a56e081dc02.png)

**Comment by slembcke** [comment] 2014-06-04 16:05
@jtwigg Any thoughts? This is one of those obnoxious issues with KVO, you can't check if something is an observer and attempting to remove something that wasn't an observer crashes.

**Comment by jtwigg** [comment] 2014-06-04 17:30
I agree that KVO has that obnoxious property. But whats surprising is that it successfully removed the previous 'for loops' observers. A unit test should expose the problem. Writing...

**Comment by jtwigg** [comment] 2014-06-04 17:46
@crmagicxxx Can you post this project to a public location so I can reproduce?
Cheers

**Comment by iMobCoding** [comment] 2014-06-04 21:19
https://dl.dropboxusercontent.com/u/5351290/ForSharing/PhysicsCrashTest.zip
Added physics node and one static node (ttf label) in the main menu. When you try moving to next scene it crashes...

Best

**Comment by jtwigg** [comment] 2014-06-04 21:58
Fixed by this pull request: https://github.com/cocos2d/cocos2d-iphone/pull/814
specficically this changelist: https://github.com/jtwigg/cocos2d-iphone/commit/f1b9245e64fd6bdbed0613dbd56f164530b7f32e

Good Catch! The problem was inconsistant use of #if define vs #ifdef define.
In the default project we use (cocos2d-ios.xcodeproj) they result in the same thing because we fill in the Preprocess Marcros section of the Build Settings.

![screen shot 2014-06-04 at 2 57 01 pm](https://cloud.githubusercontent.com/assets/1237233/3180595/3447025a-ec33-11e3-9186-bd8b618cac7b.png)
.

@crmagicxxx You seem to be using a precompiled header to do the following
#define DEBUG 0 
which a)fails #if DEBUG  and b)succeeds on #ifdef DEBUG.

I've fixed the code, but I'd recommend either using the nested project directly OR using the preprocessor macros like above.

Cheers.

**Comment by iMobCoding** [comment] 2014-06-04 22:04
I was just testing and found the same thing regarding the #if and #ifdef :) In my setup observers weren't added at all for DEBUG, that's why it worked for position/rotation and not for restricted properties...

Yes I am using precompiled header for easier changing of those macros. I hate when I have to go to Build Settings for simple thing like this. That's exactly why I am not using nested projects, so I don't have to get tons of unwanted messages in debug window...

**Comment by jtwigg** [comment] 2014-06-04 22:07
No doubt. I agree with what you said. We're just discussing right now what we want to do going forward. We'll post a new issue task shortly with our intent.

**Comment by jtwigg** [comment] 2014-06-05 21:18
New issue posted.
https://github.com/cocos2d/cocos2d-iphone/issues/818

Lets close this one please.

**Closed as completed** 2014-06-16 23:22 UTC
