### ISSUE TITLE
Physics issue present in 32 bit, not 64 bit (Cocos2D 3.3, Swift)

### ISSUE THREAD

**Issue by danielhaaser** [cocos2d/cocos2d-objc#1151] opened 2015-01-07 23:02 UTC
Demo project here (solution branch):
https://github.com/MakeGamesWithUs/FlappyBirdSwift-SpriteBuilder/tree/solution

The game crashes on iPhone 5 simulator and earlier (32-bit) after about 2 seconds.
Line 966 (CCNode.M):

``` objectivec
// Grab the origin position of the node from it's transform.
CGAffineTransform transform = NodeToPhysicsTransform(self);
physicsBody.absolutePosition = ccp(transform.tx, transform.ty);
```

`transform.ty` is a CGFloat (double on 64-bit, float in 32-bit) and has the value +Inf on the crash (in 32-bit). The app works without crashing on 64 bit simulators.

**Comment by LearnCocos2D** [comment] 2015-01-08 10:43
Since the issue is with a Swift port of Flappy Fly, maybe the port I finished just recently might serve as a repro case, to isolate whether this issue is project specific or not and to look at the differences in code/libs.

Project is here, uses cocos2d v3.4.1. I could not reproduce a crash running on iPhone 4S (iOS 7.0) Simulator.
https://drive.google.com/file/d/0B0g1SgyD5RH2Z1RmalMwN09YVTg/view?usp=sharing

**Comment by andykorth** [comment] 2015-01-08 16:16
For me, it's stopping on an assertion checking the body's position. `transform.ty` is +Inf, as you noted. If you weren't getting the assertion, maybe it wasn't in debug mode? 

The crash occurred on the iPhone 5 simulator for me. It's setting the position of the first pipe obstacle that crashes, MainScene.swift, inside https://github.com/MakeGamesWithUs/FlappyBirdSwift-SpriteBuilder/blob/solution/FlappySwift.spritebuilder/Source/MainScene.swift#L134

The obstacle.position.y is already +Inf, at that point... 

It looks like the problem is in setupRandomPosition, which:
`let random:CGFloat = (CGFloat(arc4random())/CGFloat(ARC4RANDOM_MAX))`
where random always seems to be +Inf. 

I guess this is occurring because CGFloats are floats on 32 bit systems and doubles on 64 bit systems.

`let random:CGFloat = (CGFloat(rand()) / CGFloat(RAND_MAX))`
Fixes the problem. (or a more robust fix could be done still using arc4random)

**Comment by KristenY** [comment] 2015-01-08 21:02
This is not a bug - can be fixed by using the macro in cocos2D to get a random number.
Closing this!

**Closed as completed by KristenY** 2015-01-08 21:02 UTC

**Comment by danielhaaser** [comment] 2015-01-09 06:55
Thanks everyone!  Sorry about the non-issue.
