### ISSUE TITLE
Memory leak, textures not unloading

### ISSUE THREAD

**Issue by nikitabelosludtcev** [cocos2d/cocos2d-objc#967] opened 2014-09-04 18:20 UTC
I have one scene in my test example. I replace scene every 1 second by the same scene.
I have 100 different textures and every time I add different sprite on the scene.
http://www.codeshare.io/93OKR - it's my scene code.

On iPad after preloading 80 scenes crashes with Terminated due to Memory Pressure.
http://take.ms/k43CK - it's memory usage. (No zombies enabled)
Do you know what's the problem?

I use cocos2d 3.2.

**Comment by YvesLeBorg** [comment] 2014-09-04 18:34
related to https://github.com/cocos2d/cocos2d-iphone/issues/956

**Comment by slembcke** [comment] 2014-09-04 21:21
Yep. Same issue. 3.2.1 is should be released shortly, and the issue is fixed in the v3.2 branch on GitHub.

**Closed as completed** 2014-10-02 19:29 UTC
